### PR TITLE
cppcheck 2.14: various adjustments to fix cppcheck unit test.

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01 I wanted to upload ayatana-indicator-display 24.4.0 to Debian unstable and came accross various new issues that popped up in the cppcheck unit test when running against cppcheck 2.14.0. The changes in this PR fixes those test issues.

Please provide feedback, if ok like this.

**Comment by tari01** [comment]
The gcc build is fine, but clang gives me this (I suspect it's the removal of virtuals)

```
In file included from /home/tari/Desktop/test/ayatana-indicator-display/src/service.cpp:22:
In file included from /home/tari/Desktop/test/ayatana-indicator-display/src/service.h:25:
In file included from /home/tari/Desktop/test/ayatana-indicator-display/src/indicator.h:24:
In file included from /usr/include/core/property.h:21:
In file included from /usr/include/core/signal.h:21:
In file included from /usr/include/core/connection.h:21:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:63:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/unordered_map:41:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/unordered_map.h:33:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/hashtable.h:35:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/hashtable_policy.h:39:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/ext/alloc_traits.h:34:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/alloc_traits.h:33:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/stl_construct.h:151:7: error: destructor called on non-final 'SimpleProfile' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
      __pointer->~_Tp();
      ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/alloc_traits.h:674:9: note: in instantiation of function template specialization 'std::_Destroy<SimpleProfile>' requested here
        { std::_Destroy(__p); }
               ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/shared_ptr_base.h:613:28: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<void>>::destroy<SimpleProfile>' requested here
        allocator_traits<_Alloc>::destroy(_M_impl._M_alloc(), _M_ptr());
                                  ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/shared_ptr_base.h:599:2: note: in instantiation of member function 'std::_Sp_counted_ptr_inplace<SimpleProfile, std::allocator<void>, __gnu_cxx::_S_atomic>::_M_dispose' requested here
        _Sp_counted_ptr_inplace(_Alloc __a, _Args&&... __args)
        ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/shared_ptr_base.h:972:6: note: in instantiation of function template specialization 'std::_Sp_counted_ptr_inplace<SimpleProfile, std::allocator<void>, __gnu_cxx::_S_atomic>::_Sp_counted_ptr_inplace<const char (&)[6], std::shared_ptr<_GMenuModel> &>' requested here
            _Sp_cp_type(__a._M_a, std::forward<_Args>(__args)...);
            ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/shared_ptr_base.h:1712:14: note: in instantiation of function template specialization 'std::__shared_count<>::__shared_count<SimpleProfile, std::allocator<void>, const char (&)[6], std::shared_ptr<_GMenuModel> &>' requested here
        : _M_ptr(), _M_refcount(_M_ptr, __tag, std::forward<_Args>(__args)...)
                    ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/shared_ptr.h:464:4: note: in instantiation of function template specialization 'std::__shared_ptr<SimpleProfile>::__shared_ptr<std::allocator<void>, const char (&)[6], std::shared_ptr<_GMenuModel> &>' requested here
        : __shared_ptr<_Tp>(__tag, std::forward<_Args>(__args)...)
          ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/shared_ptr.h:1009:14: note: in instantiation of function template specialization 'std::shared_ptr<SimpleProfile>::shared_ptr<std::allocator<void>, const char (&)[6], std::shared_ptr<_GMenuModel> &>' requested here
      return shared_ptr<_Tp>(_Sp_alloc_shared_tag<_Alloc>{__a},
             ^
/home/tari/Desktop/test/ayatana-indicator-display/src/service.cpp:237:20: note: in instantiation of function template specialization 'std::make_shared<SimpleProfile, const char (&)[6], std::shared_ptr<_GMenuModel> &>' requested here
    m_phone = std::make_shared<SimpleProfile>("phone", phone_menu);
                   ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/stl_construct.h:151:19: note: qualify call to silence this warning
      __pointer->~_Tp();
```

**Review by tari01 — CHANGES_REQUESTED** [review]
See build failure with Clang 16.0.6

**Comment by sunweaver** [comment]
> See build failure with Clang 16.0.6

How can I easily start a clang build?

**Comment by tari01** [comment]
> > See build failure with Clang 16.0.6
> 
> How can I easily start a clang build?

You mean, clang build of the display indicator?

```
scan-build cmake .. -DENABLE_WERROR=ON -DENABLE_TESTS=ON
scan-build --keep-cc --use-cc=clang --use-c++=clang++ make -j 4
```

**Review by tari01 — APPROVED** [review]
Builds as expected now.

**Pull request merged**
